modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/TheIllusiveC4/CorpseComplex/issues"
license="LGPL-3.0-or-later"
logoFile="${mod_icon}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors="${mod_author}"
description='''
${mod_description}
'''
[[dependencies.corpsecomplex]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.corpsecomplex]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.corpsecomplex]]
    modId="curios"
    mandatory=false
    versionRange="[1.16.5-4.0.6.0,)"
    ordering="NONE"
    side="BOTH"
